/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.forms;

import ui.forms.confirmDialogs.FDialogsConfirm;
import ui.forms.inputDialogs.FDialogsInput;
import ui.forms.messageDialogs.FDialogsMessage;
import ui.forms.optionDialogs.FDialogOption;

/**
 *
 * @author IRC_client
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBtnShowConfirm = new javax.swing.JButton();
        jBtnShowInput = new javax.swing.JButton();
        jBtnShowMessage = new javax.swing.JButton();
        jBtnShowOption = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jBtnShowConfirm.setText("Confirm Dialogs");
        jBtnShowConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnShowConfirmActionPerformed(evt);
            }
        });

        jBtnShowInput.setText("Input Dialogs");
        jBtnShowInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnShowInputActionPerformed(evt);
            }
        });

        jBtnShowMessage.setText("Message Dialogs");
        jBtnShowMessage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnShowMessageActionPerformed(evt);
            }
        });

        jBtnShowOption.setText(" Option Dialogs");
        jBtnShowOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnShowOptionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(91, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jBtnShowOption, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnShowInput, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnShowConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnShowMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(91, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jBtnShowMessage)
                .addGap(35, 35, 35)
                .addComponent(jBtnShowConfirm)
                .addGap(37, 37, 37)
                .addComponent(jBtnShowInput)
                .addGap(34, 34, 34)
                .addComponent(jBtnShowOption)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnShowMessageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnShowMessageActionPerformed
        new FDialogsMessage().setVisible(true);
    }//GEN-LAST:event_jBtnShowMessageActionPerformed

    private void jBtnShowOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnShowOptionActionPerformed
        new FDialogOption().setVisible(true);
    }//GEN-LAST:event_jBtnShowOptionActionPerformed

    private void jBtnShowConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnShowConfirmActionPerformed
        new FDialogsConfirm().setVisible(true);
    }//GEN-LAST:event_jBtnShowConfirmActionPerformed

    private void jBtnShowInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnShowInputActionPerformed
        new FDialogsInput().setVisible(true);
    }//GEN-LAST:event_jBtnShowInputActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnShowConfirm;
    private javax.swing.JButton jBtnShowInput;
    private javax.swing.JButton jBtnShowMessage;
    private javax.swing.JButton jBtnShowOption;
    // End of variables declaration//GEN-END:variables
}
