/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.forms.messageDialogs;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author IRC_client
 */
public class FDialogsMessage extends javax.swing.JFrame {

    /**
     * Creates new form FDialogsMessage
     */
    public FDialogsMessage() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Message dijaloge koristimo kada želimo korisniku da prikažemo određenu poruku.");

        jButton1.setText("Message Dialog 1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton4.setText("Message Dialog 1");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Message Dialog 1");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addComponent(jButton4)
                            .addComponent(jButton5))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(35, 35, 35)
                .addComponent(jButton1)
                .addGap(26, 26, 26)
                .addComponent(jButton4)
                .addGap(26, 26, 26)
                .addComponent(jButton5)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
//      Prvi overload metode showMessageDialog omogucava da podesimo roditeljsku formu i poruku na dijalogu
//      showMessageDialog(Component parentComponent, Object message)
        JOptionPane.showMessageDialog(this, "Poruka message dijaloga 1");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
//      Drugi overload metode showMessageDialog omogucava da podesimo roditeljsku formu, poruku, nalov i vrstu poruke na dijalogu
//      showMessageDialog(Component parentComponent, Object message, String title, int messageType)
        JOptionPane.showMessageDialog(this, "Poruka message dijaloga 2", "Nalov message dijaloga 2", JOptionPane.PLAIN_MESSAGE);
//        JOptionPane.showMessageDialog(this, "Poruka message dijaloga 2", "Nalov message dijaloga 2", JOptionPane.WARNING_MESSAGE);
//        JOptionPane.showMessageDialog(this, "Poruka message dijaloga 2", "Nalov message dijaloga 2", JOptionPane.INFORMATION_MESSAGE);
//        JOptionPane.showMessageDialog(this, "Poruka message dijaloga 2", "Nalov message dijaloga 2", JOptionPane.ERROR_MESSAGE);
//        JOptionPane.showMessageDialog(this, "Poruka message dijaloga 2", "Nalov message dijaloga 2", JOptionPane.QUESTION_MESSAGE);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
//      Treci overload metode showMessageDialog omogucava da podesimo roditeljsku formu, poruku, naslov, 
//      vrstu poruke na dijalogu kao i da dodamo svoju ikonicu po zelji
//      showMessageDialog(Component parentComponent, Object message, String title, int messageType, Icon icon)
        ImageIcon icon = new ImageIcon("src/resources/java.png");
        JOptionPane.showMessageDialog(this, "Poruka message dijaloga 3", "Nalov message dijaloga 3", JOptionPane.WARNING_MESSAGE, icon);
    }//GEN-LAST:event_jButton5ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
