/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.forms.confirmDialogs;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author IRC_client
 */
public class FDialogsConfirm extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public FDialogsConfirm() {
        initComponents();
        this.setLocationRelativeTo(getParent());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBtnConfirm1 = new javax.swing.JButton();
        jBtnConfirm2 = new javax.swing.JButton();
        jBtnConfirm3 = new javax.swing.JButton();
        jBtnConfirm4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jBtnConfirm5 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLblMessage1 = new javax.swing.JLabel();
        jLblMessage2 = new javax.swing.JLabel();
        jLblMessage3 = new javax.swing.JLabel();
        jLblMessage4 = new javax.swing.JLabel();
        jLblMessage5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jBtnConfirm1.setText("Confirm 1");
        jBtnConfirm1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnConfirm1ActionPerformed(evt);
            }
        });

        jBtnConfirm2.setText("Confirm 2");
        jBtnConfirm2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnConfirm2ActionPerformed(evt);
            }
        });

        jBtnConfirm3.setText("Confirm 3");
        jBtnConfirm3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnConfirm3ActionPerformed(evt);
            }
        });

        jBtnConfirm4.setText("Confirm 4");
        jBtnConfirm4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnConfirm4ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Confirm dijaloge koristimo kada želimo da dobijemo od korisnika odgovor na postavljeno pitanje.");

        jLabel2.setText("Odgovor korisnika:");

        jLabel3.setText("Odgovor korisnika:");

        jLabel4.setText("Odgovor korisnika:");

        jLabel5.setText("Odgovor korisnika:");

        jBtnConfirm5.setText("Confirm 5");
        jBtnConfirm5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnConfirm5ActionPerformed(evt);
            }
        });

        jLabel6.setText("Odgovor korisnika:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLblMessage1.setBackground(new java.awt.Color(153, 204, 255));
        jLblMessage1.setToolTipText("");
        jLblMessage1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLblMessage2.setBackground(new java.awt.Color(153, 204, 255));
        jLblMessage2.setToolTipText("");
        jLblMessage2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLblMessage3.setBackground(new java.awt.Color(153, 204, 255));
        jLblMessage3.setToolTipText("");
        jLblMessage3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLblMessage4.setBackground(new java.awt.Color(153, 204, 255));
        jLblMessage4.setToolTipText("");
        jLblMessage4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLblMessage5.setBackground(new java.awt.Color(153, 204, 255));
        jLblMessage5.setToolTipText("");
        jLblMessage5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBtnConfirm1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtnConfirm2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtnConfirm3, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtnConfirm4, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtnConfirm5, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(jLblMessage4, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(jLblMessage3, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(jLblMessage2, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jLblMessage1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(jLblMessage5, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jBtnConfirm1)
                                .addComponent(jLabel2))
                            .addComponent(jLblMessage1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBtnConfirm2)
                            .addComponent(jLabel3)))
                    .addComponent(jLblMessage2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBtnConfirm3)
                        .addComponent(jLabel5))
                    .addComponent(jLblMessage3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBtnConfirm4)
                        .addComponent(jLabel4))
                    .addComponent(jLblMessage4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBtnConfirm5)
                        .addComponent(jLabel6))
                    .addComponent(jLblMessage5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnConfirm1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnConfirm1ActionPerformed
//      Prvi overload metode showCofirmDialog omogucava da podesimo roditeljsku formu i poruku na dijalogu
//      showConfirmDialog(Component parentComponent, Object message)
        int answer = JOptionPane.showConfirmDialog(this, "Poruka confirm dijaloga 1");
        String answerString = switchUserAnswerYESNO(answer);
        jLblMessage1.setText(answer+": "+answerString);
    }//GEN-LAST:event_jBtnConfirm1ActionPerformed

    private void jBtnConfirm2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnConfirm2ActionPerformed
//      Drugi overload metode showCofirmDialog omogucava da podesimo roditeljsku formu,
//      poruku, naslov dijaloga i predefinisani skup dugmica
//      showConfirmDialog(Component parentComponent, Object message, String title, int optionType)
        int answer = JOptionPane.showConfirmDialog(this, "Poruka confirm dijaloga 2", "Naslov confirm dijaloga 2", JOptionPane.DEFAULT_OPTION);
        String answerString = switchUserAnswerOK(answer);
        jLblMessage2.setText(answer+": "+answerString);
    }//GEN-LAST:event_jBtnConfirm2ActionPerformed

    private void jBtnConfirm3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnConfirm3ActionPerformed
//      Treci overload metode showCofirmDialog omogucava  da podesimo roditeljsku formu, poruku, naslov dijaloga, 
//      skup predefinisanih dugmica i vrstu dijaloga koja odredjuje koja se od predefinisanih ikonica prikazuje  
//      showConfirmDialog(Component parentComponent, Object message, String title, int optionType, int messageType)
        int answer = JOptionPane.showConfirmDialog(this, "Poruka confirm dijaloga 3", "Naslov confirm dijaloga 3", JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE);
        String answerString = switchUserAnswerYESNO(answer);
        jLblMessage3.setText(answer+": "+answerString); 
    }//GEN-LAST:event_jBtnConfirm3ActionPerformed

    private void jBtnConfirm4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnConfirm4ActionPerformed
//      Cetvrti overload metode showCofirmDialog omogucava da podesimo roditeljsku formu, poruku, naslov dijaloga, 
//      skup predefinisanih dugmica kao i da na dijalog prikazemo ikonicu po zelji  
//      showConfirmDialog(Component parentComponent, Object message, String title, int optionType, int messageType, Icon icon)
        ImageIcon icon = new ImageIcon("src/resources/java.png");
        int answer = JOptionPane.showConfirmDialog(this, "Poruka confirm dijaloga 4", "Naslov confirm dijaloga 4", JOptionPane.YES_NO_CANCEL_OPTION, -1, icon);
        String answerString = switchUserAnswerYESNO(answer);
        jLblMessage4.setText(answer+": "+answerString); 
    }//GEN-LAST:event_jBtnConfirm4ActionPerformed

    private void jBtnConfirm5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnConfirm5ActionPerformed
        ImageIcon icon = new ImageIcon("src/resources/java.png");
        int answer = JOptionPane.showConfirmDialog(this, "Poruka confirm dijaloga 5", "Naslov confirm dijaloga 5", JOptionPane.OK_CANCEL_OPTION, -1, icon);
        String answerString = switchUserAnswerOK(answer);
        jLblMessage5.setText(answer+": "+answerString); 
    }//GEN-LAST:event_jBtnConfirm5ActionPerformed

//    Definisane su 2 posebne metode iz razloga sto konstante YES i OK imaju istu vrednost, 0 
//    (jer se nikad ne nalaze zajedno u predefinisianim kombinacijama dugmica koje korisnik moze izabrati).
    private String switchUserAnswerYESNO(int answer) {
        if (answer == JOptionPane.YES_OPTION) {
            return "Yes";
        }
        if (answer == JOptionPane.NO_OPTION) {
            return "No";
        }
        if (answer == JOptionPane.CANCEL_OPTION) {
            return "Cancel";
        }
        if (answer == JOptionPane.CLOSED_OPTION) {
            return "Closed";
        }
        return "";
    }
    
    private String switchUserAnswerOK(int answer) {
        if (answer == JOptionPane.OK_OPTION) {
            return "OK";
        }
        if (answer == JOptionPane.CANCEL_OPTION) {
            return "Cancel";
        }
        if (answer == JOptionPane.CLOSED_OPTION) {
            return "Closed";
        }
        return "";
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnConfirm1;
    private javax.swing.JButton jBtnConfirm2;
    private javax.swing.JButton jBtnConfirm3;
    private javax.swing.JButton jBtnConfirm4;
    private javax.swing.JButton jBtnConfirm5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLblMessage1;
    private javax.swing.JLabel jLblMessage2;
    private javax.swing.JLabel jLblMessage3;
    private javax.swing.JLabel jLblMessage4;
    private javax.swing.JLabel jLblMessage5;
    // End of variables declaration//GEN-END:variables
}
