/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.forms.inputDialogs;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import resources.Fruit;

/**
 *
 * @author IRC_client
 */
public class FDialogsInput extends javax.swing.JFrame {

    /**
     * Creates new form FInputDialogs
     */
    public FDialogsInput() {
        initComponents();
        setLocationRelativeTo(getParent());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBtnOption1 = new javax.swing.JButton();
        jLblMessage1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jBtnOption2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLblMessage2 = new javax.swing.JLabel();
        jLblMessage3 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jBtnOption3 = new javax.swing.JButton();
        jBtnOption4 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLblMessage4 = new javax.swing.JLabel();
        jBtnOption5 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLblMessage5 = new javax.swing.JLabel();
        jLblMessage6 = new javax.swing.JLabel();
        jBtnOption6 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jBtnOption7 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLblMessage7 = new javax.swing.JLabel();
        jBtnOption8 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLblMessage8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jBtnOption1.setText(" Input Dialog 1");
        jBtnOption1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnOption1ActionPerformed(evt);
            }
        });

        jLblMessage1.setBackground(new java.awt.Color(153, 204, 255));
        jLblMessage1.setToolTipText("");
        jLblMessage1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Poruka korisnika:");

        jBtnOption2.setText(" Input Dialog 2");
        jBtnOption2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnOption2ActionPerformed(evt);
            }
        });

        jLabel2.setText("Poruka korisnika:");

        jLblMessage2.setBackground(new java.awt.Color(153, 204, 255));
        jLblMessage2.setToolTipText("");
        jLblMessage2.setAutoscrolls(true);
        jLblMessage2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLblMessage3.setBackground(new java.awt.Color(153, 204, 255));
        jLblMessage3.setToolTipText("");
        jLblMessage3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setText("Poruka korisnika:");

        jBtnOption3.setText("Input Dialog 3");
        jBtnOption3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnOption3ActionPerformed(evt);
            }
        });

        jBtnOption4.setText(" Input Dialog 4");
        jBtnOption4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnOption4ActionPerformed(evt);
            }
        });

        jLabel4.setText("Poruka korisnika:");

        jLblMessage4.setBackground(new java.awt.Color(153, 204, 255));
        jLblMessage4.setToolTipText("");
        jLblMessage4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jBtnOption5.setText(" Input Dialog 5");
        jBtnOption5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnOption5ActionPerformed(evt);
            }
        });

        jLabel5.setText("Poruka korisnika:");

        jLblMessage5.setBackground(new java.awt.Color(153, 204, 255));
        jLblMessage5.setToolTipText("");
        jLblMessage5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLblMessage6.setBackground(new java.awt.Color(153, 204, 255));
        jLblMessage6.setToolTipText("");
        jLblMessage6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jBtnOption6.setText(" Input Dialog 6.1");
        jBtnOption6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnOption6ActionPerformed(evt);
            }
        });

        jLabel6.setText("Izbor korisnika:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Ulaz dobijen od korisnika je povratna vrednost metode showInputDialog.");

        jBtnOption7.setText(" Input Dialog 6.2");
        jBtnOption7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnOption7ActionPerformed(evt);
            }
        });

        jLabel8.setText("Izbor korisnika:");

        jLblMessage7.setBackground(new java.awt.Color(153, 204, 255));
        jLblMessage7.setToolTipText("");
        jLblMessage7.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jBtnOption8.setText(" Input Dialog 6.3");
        jBtnOption8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnOption8ActionPerformed(evt);
            }
        });

        jLabel9.setText("Poruka korisnika:");

        jLblMessage8.setBackground(new java.awt.Color(153, 204, 255));
        jLblMessage8.setToolTipText("");
        jLblMessage8.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Input dijaloge koristimo kada želimo da prikupimo neki podatak ili izbor (ulaz) od korisnika.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBtnOption1)
                                .addGap(55, 55, 55)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLblMessage1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBtnOption2)
                                .addGap(55, 55, 55)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLblMessage2, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBtnOption3)
                                .addGap(55, 55, 55)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLblMessage3, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBtnOption4)
                                .addGap(55, 55, 55)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLblMessage4, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBtnOption5)
                                .addGap(55, 55, 55)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLblMessage5, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBtnOption6)
                                .addGap(55, 55, 55)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLblMessage6, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBtnOption7)
                                .addGap(55, 55, 55)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLblMessage7, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBtnOption8)
                                .addGap(55, 55, 55)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLblMessage8, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel7))))
                .addContainerGap(94, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLblMessage1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBtnOption1)
                        .addComponent(jLabel1)))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLblMessage2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBtnOption2)
                        .addComponent(jLabel2)))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLblMessage3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBtnOption3)
                        .addComponent(jLabel3)))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLblMessage4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBtnOption4)
                        .addComponent(jLabel4)))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLblMessage5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBtnOption5)
                        .addComponent(jLabel5)))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnOption6)
                    .addComponent(jLblMessage6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBtnOption7)
                        .addComponent(jLabel8))
                    .addComponent(jLblMessage7, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBtnOption8)
                        .addComponent(jLabel9))
                    .addComponent(jLblMessage8, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnOption1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnOption1ActionPerformed
//     Prvi overload metode showInputDialog omogucava da podesimo samo poruku na dijalogu  
//     showInputDialog(Object message)   
        String usersMessage = JOptionPane.showInputDialog("Poruka input dijaloga 1");
        jLblMessage1.setText(usersMessage);
    }//GEN-LAST:event_jBtnOption1ActionPerformed

    private void jBtnOption2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnOption2ActionPerformed
//     Drugi overload metode showInputDialog omogucava da podesimo poruku na dijalogu i 
//     roditeljsku formu dijaloga 
//     showInputDialog(Component parentComponent, Object message) 
        String usersMessage = JOptionPane.showInputDialog(this, "Poruka input dijaloga 2");
        jLblMessage2.setText(usersMessage);
    }//GEN-LAST:event_jBtnOption2ActionPerformed

    private void jBtnOption3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnOption3ActionPerformed
//     Treci overload metode showInputDialog omogucava da podesimo poruku na dijalogu i podrazumevanu vrednost ulaza koji korisnik unosi 
//     showInputDialog(Object message, Object initialSelectionValue)
        String usersMessage = JOptionPane.showInputDialog("Poruka input dijaloga 3", "podrazumevana poruka korisnika");
        jLblMessage3.setText(usersMessage);
    }//GEN-LAST:event_jBtnOption3ActionPerformed

    private void jBtnOption4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnOption4ActionPerformed
//     Cetvrti overload metode showInputDialog omogucava da podesimo roditeljsku formu dijaloga,
//     poruku na dijalogu i podrazumevanu vrednost ulaza koji korisnik unosi 
//     showInputDialog(Component parentComponent, Object message, Object initialSelectionValue)
        String usersMessage = JOptionPane.showInputDialog(this, "Poruka input dijaloga 4", "podrazumevana poruka korisnika");
        jLblMessage4.setText(usersMessage);
    }//GEN-LAST:event_jBtnOption4ActionPerformed

    private void jBtnOption5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnOption5ActionPerformed
//     Peti overload metode showInputDialog omogucava da podesimo roditeljsku formu dijaloga,
//     poruku na dijalogu, nalov dijaloga i vrstu poruke u zavisnosti od koje ce se postaviti neka od
//     predefinisanih ikonica   
//     showInputDialog(Component parentComponent, Object message, String title, int messageType)
        String usersMessage = JOptionPane.showInputDialog(null, "Poruka input dijaloga 5", "Naslov input dijaloga 5", JOptionPane.WARNING_MESSAGE);
        jLblMessage5.setText(usersMessage);
    }//GEN-LAST:event_jBtnOption5ActionPerformed

    private void jBtnOption6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnOption6ActionPerformed
//     Sesti overload metode showInputDialog omogućava nam da podesimo sve: roditeljsku formu dijaloga,
//     poruku na dijalogu, nalov dijaloga i vrstu poruke, ikonicu po zelji umesto predefinisane, 
//     tip komponente pomocu koje korisnik unosi ulaz kao i podrazumevanu vrednost ulaza koji korisnik unosi 
//     showInputDialog(Component parentComponent, Object message, String title, int messageType, Icon icon, Object[] selectionValues, Object initialSelectionValue)
        ImageIcon icon = new ImageIcon("src/resources/java.png");

//      Ova metoda nam omogucava da putem formalnog parametra selectionValues prosledimo listu opcija za korisnika koje ce se prikazati u JComboBox-u odakle treba da izabere jednu opciju
//      Opcije treba da prosledimo u nizu jer je tip selectionValues parametra Object[], niz objekata klase Object, nadklase svih klasa u Javi, te zbog toga mozemo da prosledimo
//      niz objekata bilo koje klase
//      Pomocu parametra initialSelectionValue prosledjujemo referencu objekta iz niza selectionValues koji zelimo da bude prikazan kao podrazumevani izbor (taj objekat je 
//      selektovan kada se prikaze dijalog)
        String[] choices = {"Prvi izbor", "drugi izbor", "treci izbor"};
        Object input = JOptionPane.showInputDialog(this, "Poruka input dijaloga 6.1", "Nalov input dijaloga 6.1", -1, icon, choices, null);
        
//      Napomena: ova provera je dodata jer je povratna vrednost ovog overload-a metode objekat klase Object (za razliku od ostalih overload-ova koji vracaju String) 
//      i vraca null ukoliko korisnik nije odabrao neku opciju iz opadajuce liste vec je samo zatvorio dijalog (promenljiva input bi imala vrednost null)
        if (input != null) {
            jLblMessage6.setText(input.toString());
        }
//        

    }//GEN-LAST:event_jBtnOption6ActionPerformed

    private void jBtnOption7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnOption7ActionPerformed

        Fruit apple = new Fruit("apple", "green");
        Fruit pear = new Fruit("pear", "yellow");
        Fruit plum = new Fruit("plum", "purple");
        Fruit[] choices = new Fruit[]{apple, pear, plum};

//      Kao selectionValues parametar prosledjujemo niz objekata klase Fruit, oni ce biti prikazani u JComboBox-u tako sto ce za svaki biti pozvana toString metoda
//      Kao initialSelectionValue prosledjujemo referencu plum (koja je u nizu koji prosledjujemo kao selectionValues) i zbog toga ce po prikazivanju dijaloga
//      selektovana opcija biti objekat cija se referenca cuva u promenljivoj plum
        Object input = JOptionPane.showInputDialog(this, "Poruka input dijaloga 6.2", "Nalov input dijaloga 6.2", JOptionPane.QUESTION_MESSAGE, null, choices, plum);

        if (input != null) {
            Fruit usersMessage = (Fruit) input;
            jLblMessage7.setText(usersMessage.toString());
        }
    }//GEN-LAST:event_jBtnOption7ActionPerformed

    private void jBtnOption8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnOption8ActionPerformed
//      Kada za parametar selectionValues prosledimo null, na dijalogu se kreira JTextField za unos podataka i vrednost parametra initialSelection
//      se u to polje upisuje kao podrazumevana poruka
        
//      Ovde je i za parametar icon prosledjena null vrednost posto je parametrom messageType vec definisan prikaz neke od predefinisanih ikonica  
        String usersMessage =  JOptionPane.showInputDialog(this, "Poruka input dijaloga 6.3", "Nalov input dijaloga 6.3", JOptionPane.ERROR_MESSAGE, null, null, "Podrazumevana poruka korisnika").toString();
        jLblMessage8.setText(usersMessage);
    }//GEN-LAST:event_jBtnOption8ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnOption1;
    private javax.swing.JButton jBtnOption2;
    private javax.swing.JButton jBtnOption3;
    private javax.swing.JButton jBtnOption4;
    private javax.swing.JButton jBtnOption5;
    private javax.swing.JButton jBtnOption6;
    private javax.swing.JButton jBtnOption7;
    private javax.swing.JButton jBtnOption8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLblMessage1;
    private javax.swing.JLabel jLblMessage2;
    private javax.swing.JLabel jLblMessage3;
    private javax.swing.JLabel jLblMessage4;
    private javax.swing.JLabel jLblMessage5;
    private javax.swing.JLabel jLblMessage6;
    private javax.swing.JLabel jLblMessage7;
    private javax.swing.JLabel jLblMessage8;
    // End of variables declaration//GEN-END:variables
}
